"""create analysis history table

Revision ID: 2aaac5af5997
Revises: 
Create Date: 2026-08-24 23:08:37.772769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaac5af5997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=True),
    sa.Column('sender', sa.String(length=512), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name='ck_analysis_risk_level'),
    sa.CheckConstraint('finding_count >= 0', name='ck_analysis_finding_count'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_analysis_risk_score'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_records_file_sha256'), ['file_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_records_risk_level'), ['risk_level'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_records_risk_level'))
        batch_op.drop_index(batch_op.f('ix_analysis_records_file_sha256'))
        batch_op.drop_index(batch_op.f('ix_analysis_records_created_at'))

    op.drop_table('analysis_records')
    # ### end Alembic commands ###
